### ISSUE TITLE
LED activity

### ISSUE THREAD

**Issue by otofoto** [lmdpua/CP2112-Laptop-Battery-Reader#1]
On some CP2112 adapters GPIO1 and GPIO2 is used for LEDs to show RX and TX activity. 
Need to configure GPIO ports 0,1 as output on start to enable these LEDs.

**Comment by lmdpua** [comment]
> On some CP2112 adapters GPIO1 and GPIO2 is used for LEDs to show RX and TX activity. Need to configure GPIO ports 0,1 as output on start to enable these LEDs.

Thanks for the tip! I could not figure out how to make them blink in any way. I will try

**Comment by otofoto** [comment]
Python example for blinking leds using hidapi is here:
https://github.com/artizirk/cp2112/blob/master/main.py

**Comment by lmdpua** [comment]
I figured out how to make the LEDs blink and implemented this feature in the latest version. Thank you for the tip.
