### ISSUE TITLE
SPI/SMBUS EEPROM read/write

### ISSUE THREAD

**Issue by otofoto** [lmdpua/CP2112-Laptop-Battery-Reader#2]
Looking for solution to read/write 24Cxx/93Cxx eeproms

**Comment by lmdpua** [comment]
These eeproms operate on the i2c protocol, so they can also be read using cp2112. Do not forget that the device address must be shifted to the left by one bit (ADDR << 1). Since the zero bit is used by the library to indicate writing or reading. Also the bus speed can be increased up to 400kHz

**Comment by otofoto** [comment]
93Cxx are SPI so have not found how to configure GPIO for SPI write.

**Comment by lmdpua** [comment]
For SPI you need another chip
https://www.silabs.com/documents/public/data-sheets/CP2130.pdf

**Comment by lmdpua** [comment]
Although ... I was thinking. Having a lot of GPIOs and sufficient skill, you can write a software implementation of the SPI. But in this case, you can forget about DMA.

**Comment by otofoto** [comment]
CP2130 is for hardware implementation. Software SPI can be implemented using GPIO just need to find example.
Like this - https://github.com/gsimon75-iot/PL2303-GPIO/blob/master/spi_eeprom.cc

Skill is what I am lacking. Barely can compile those examples.
